---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bluegreen-demo.fullname" . }}
  labels:
    app: {{ template "bluegreen-demo.name" . }}
    chart: {{ template "bluegreen-demo.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ template "bluegreen-demo.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bluegreen-demo.fullname" . }}-preview
  labels:
    app: {{ template "bluegreen-demo.name" . }}
    chart: {{ template "bluegreen-demo.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ template "bluegreen-demo.name" . }}
    release: {{ .Release.Name }}
