replicaCount: 2

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

app:
  title: "Helm Guestbook updated"
  subtitle: "Helm Chart"
  color: "#3498db"
  description: "This app is deployed using a Helm chart. Values can be overridden per environment. ArgoCD renders the chart and tracks drift."

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
