# Todo App — Blue-Green with Chaos Testing
replicaCount: 2

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

image:
  repository: todo-api
  tag: "latest"
  pullPolicy: Never

postgres:
  image:
    repository: postgres
    tag: "16-alpine"
  db: tododb
  user: todouser
  password: todopass
  storage: 256Mi

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
